name: "tu6ge/publish-action"
description: "Auto publish cargo package when you push a new version in Cargo.toml, and tag it with that version."

runs:
  using: node20
  main: dist/bundle/index.js

outputs:
  new_version:
    description: "Whether a new version was detected"
  publish:
    description: "Whether the publish succeeded"
  new_version_value:
    description: "The new version string, e.g. 1.2.3"
