name: 'publish-action'
description: 'Auto publish cargo when git push new version in cargo.toml , and tagging it by this version'
branding:
  icon: 'arrow-up-circle'  # 图标的名称，不需要后缀
  color: 'blue'  # 可以选择图标颜色
inputs:
  DIR: 
    description: 'Crate package dirname'
    required: false
    default: "/"
  TAG_PREFIX:
    description: "The tag prefix to be generated"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'docker://ghcr.io/tu6ge/publish-action:v0.4.12'
